const alunas = [
  {
    "nome": "Sophie Peixoto",
    "idade": 42,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 3,
    "genêro": "feminino",
    "id": 31,
    "mes_cancelamento": null,
    "mes_entrada": 9,
    "status": "ativo",
    "ultima_presenca": 9164537,
    "vai_evadir": "não"
  },
  
  {
    "nome": "Emanuella Silva",
    "idade": 37,
    "contrato_meses": 12,
    "feedback": "não",
    "frequência": 5,
    "genêro": "feminino",
    "id": 32,
    "mes_cancelamento": null,
    "mes_entrada": 4,
    "status": "ativo",
    "ultima_presenca": 9479264,
    "vai_evadir": "sim"
  },
  {
    "nome": "Ana Clara Rodrigues",
    "idade": 25,
    "contrato_meses": 6,
    "feedback": "sim",
    "frequência": 4,
    "genêro": "feminino",
    "id": 33,
    "mes_cancelamento": null,
    "mes_entrada": 2,
    "status": "ativo",
    "ultima_presenca": 9578231,
    "vai_evadir": "não"
  },
  {
    "nome": "Beatriz Almeida",
    "idade": 31,
    "contrato_meses": 12,
    "feedback": "não",
    "frequência": 2,
    "genêro": "feminino",
    "id": 34,
    "mes_cancelamento": 5,
    "mes_entrada": 1,
    "status": "cancelado",
    "ultima_presenca": 9273645,
    "vai_evadir": "sim"
  },
  {
    "nome": "Camila Costa",
    "idade": 29,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 5,
    "genêro": "feminino",
    "id": 35,
    "mes_cancelamento": null,
    "mes_entrada": 3,
    "status": "ativo",
    "ultima_presenca": 9674521,
    "vai_evadir": "não"
  },
  {
    "nome": "Daniela Oliveira",
    "idade": 35,
    "contrato_meses": 6,
    "feedback": "não",
    "frequência": 3,
    "genêro": "feminino",
    "id": 36,
    "mes_cancelamento": null,
    "mes_entrada": 7,
    "status": "ativo",
    "ultima_presenca": 9871234,
    "vai_evadir": "sim"
  },
  {
    "nome": "Eduarda Santos",
    "idade": 27,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 4,
    "genêro": "feminino",
    "id": 37,
    "mes_cancelamento": null,
    "mes_entrada": 5,
    "status": "ativo",
    "ultima_presenca": 9576321,
    "vai_evadir": "não"
  },
  {
    "nome": "Fernanda Lima",
    "idade": 33,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 5,
    "genêro": "feminino",
    "id": 38,
    "mes_cancelamento": null,
    "mes_entrada": 8,
    "status": "ativo",
    "ultima_presenca": 9975362,
    "vai_evadir": "não"
  },
  {
    "nome": "Gabriela Pereira",
    "idade": 40,
    "contrato_meses": 6,
    "feedback": "não",
    "frequência": 1,
    "genêro": "feminino",
    "id": 39,
    "mes_cancelamento": 3,
    "mes_entrada": 1,
    "status": "cancelado",
    "ultima_presenca": 9078563,
    "vai_evadir": "sim"
  },
  {
    "nome": "Heloísa Martins",
    "idade": 26,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 4,
    "genêro": "feminino",
    "id": 40,
    "mes_cancelamento": null,
    "mes_entrada": 6,
    "status": "ativo",
    "ultima_presenca": 9678542,
    "vai_evadir": "não"
  },
  {
    "nome": "Isabela Souza",
    "idade": 32,
    "contrato_meses": 12,
    "feedback": "não",
    "frequência": 2,
    "genêro": "feminino",
    "id": 41,
    "mes_cancelamento": 7,
    "mes_entrada": 2,
    "status": "cancelado",
    "ultima_presenca": 9378564,
    "vai_evadir": "sim"
  },
  {
    "nome": "Juliana Ferreira",
    "idade": 28,
    "contrato_meses": 6,
    "feedback": "sim",
    "frequência": 5,
    "genêro": "feminino",
    "id": 42,
    "mes_cancelamento": null,
    "mes_entrada": 9,
    "status": "ativo",
    "ultima_presenca": 9174536,
    "vai_evadir": "não"
  },
  {
    "nome": "Larissa Gonçalves",
    "idade": 38,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 3,
    "genêro": "feminino",
    "id": 43,
    "mes_cancelamento": null,
    "mes_entrada": 4,
    "status": "ativo",
    "ultima_presenca": 9478563,
    "vai_evadir": "não"
  },
  {
    "nome": "Mariana Alves",
    "idade": 24,
    "contrato_meses": 6,
    "feedback": "não",
    "frequência": 4,
    "genêro": "feminino",
    "id": 44,
    "mes_cancelamento": null,
    "mes_entrada": 7,
    "status": "ativo",
    "ultima_presenca": 9774536,
    "vai_evadir": "sim"
  },
  {
    "nome": "Natália Ribeiro",
    "idade": 36,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 5,
    "genêro": "feminino",
    "id": 45,
    "mes_cancelamento": null,
    "mes_entrada": 5,
    "status": "ativo",
    "ultima_presenca": 9578642,
    "vai_evadir": "não"
  },
  {
    "nome": "Patrícia Nunes",
    "idade": 30,
    "contrato_meses": 12,
    "feedback": "não",
    "frequência": 1,
    "genêro": "feminino",
    "id": 46,
    "mes_cancelamento": 4,
    "mes_entrada": 1,
    "status": "cancelado",
    "ultima_presenca": 9274536,
    "vai_evadir": "sim"
  },
  {
    "nome": "Rafaela Costa",
    "idade": 29,
    "contrato_meses": 6,
    "feedback": "sim",
    "frequência": 4,
    "genêro": "feminino",
    "id": 47,
    "mes_cancelamento": null,
    "mes_entrada": 8,
    "status": "ativo",
    "ultima_presenca": 9874536,
    "vai_evadir": "não"
  },
  {
    "nome": "Tatiane Silva",
    "idade": 34,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 3,
    "genêro": "feminino",
    "id": 48,
    "mes_cancelamento": null,
    "mes_entrada": 3,
    "status": "ativo",
    "ultima_presenca": 9374536,
    "vai_evadir": "não"
  },
  {
    "nome": "Vanessa Oliveira",
    "idade": 27,
    "contrato_meses": 12,
    "feedback": "não",
    "frequência": 2,
    "genêro": "feminino",
    "id": 49,
    "mes_cancelamento": 6,
    "mes_entrada": 2,
    "status": "cancelado",
    "ultima_presenca": 9474536,
    "vai_evadir": "sim"
  },
  {
    "nome": "Alice Pereira",
    "idade": 31,
    "contrato_meses": 6,
    "feedback": "sim",
    "frequência": 5,
    "genêro": "feminino",
    "id": 50,
    "mes_cancelamento": null,
    "mes_entrada": 10,
    "status": "ativo",
    "ultima_presenca": 9074536,
    "vai_evadir": "não"
  },
  {
    "nome": "Bianca Carvalho",
    "idade": 28,
    "contrato_meses": 12,
    "feedback": "não",
    "frequência": 3,
    "genêro": "feminino",
    "id": 51,
    "mes_cancelamento": null,
    "mes_entrada": 7,
    "status": "ativo",
    "ultima_presenca": 9774536,
    "vai_evadir": "sim"
  },
  {
    "nome": "Carolina Rocha",
    "idade": 35,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 4,
    "genêro": "feminino",
    "id": 52,
    "mes_cancelamento": null,
    "mes_entrada": 5,
    "status": "ativo",
    "ultima_presenca": 9574536,
    "vai_evadir": "não"
  },
  {
    "nome": "Débora Moreira",
    "idade": 29,
    "contrato_meses": 6,
    "feedback": "não",
    "frequência": 2,
    "genêro": "feminino",
    "id": 53,
    "mes_cancelamento": 4,
    "mes_entrada": 2,
    "status": "cancelado",
    "ultima_presenca": 9374536,
    "vai_evadir": "sim"
  },
  {
    "nome": "Elaine Castro",
    "idade": 33,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 5,
    "genêro": "feminino",
    "id": 54,
    "mes_cancelamento": null,
    "mes_entrada": 9,
    "status": "ativo",
    "ultima_presenca": 9974536,
    "vai_evadir": "não"
  },
  {
    "nome": "Flávia Duarte",
    "idade": 26,
    "contrato_meses": 6,
    "feedback": "sim",
    "frequência": 3,
    "genêro": "feminino",
    "id": 55,
    "mes_cancelamento": null,
    "mes_entrada": 8,
    "status": "ativo",
    "ultima_presenca": 9874536,
    "vai_evadir": "não"
  },
  {
    "nome": "Giovanna Melo",
    "idade": 37,
    "contrato_meses": 12,
    "feedback": "não",
    "frequência": 1,
    "genêro": "feminino",
    "id": 56,
    "mes_cancelamento": 5,
    "mes_entrada": 3,
    "status": "cancelado",
    "ultima_presenca": 9574536,
    "vai_evadir": "sim"
  },
  {
    "nome": "Helena Barbosa",
    "idade": 30,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 4,
    "genêro": "feminino",
    "id": 57,
    "mes_cancelamento": null,
    "mes_entrada": 6,
    "status": "ativo",
    "ultima_presenca": 9674536,
    "vai_evadir": "não"
  },
  {
    "nome": "Iris Cardoso",
    "idade": 24,
    "contrato_meses": 6,
    "feedback": "não",
    "frequência": 2,
    "genêro": "feminino",
    "id": 58,
    "mes_cancelamento": null,
    "mes_entrada": 4,
    "status": "ativo",
    "ultima_presenca": 9474536,
    "vai_evadir": "sim"
  },
  {
    "nome": "Júlia Mendes",
    "idade": 32,
    "contrato_meses": 12,
    "feedback": "sim",
    "frequência": 5,
    "genêro": "feminino",
    "id": 59,
    "mes_cancelamento": null,
    "mes_entrada": 11,
    "status": "ativo",
    "ultima_presenca": 9174536,
    "vai_evadir": "não"
  },
  {
    "nome": "Karen Teixeira",
    "idade": 28,
    "contrato_meses": 12,
    "feedback": "não",
    "frequência": 3,
    "genêro": "feminino",
    "id": 60,
    "mes_cancelamento": 8,
    "mes_entrada": 5,
    "status": "cancelado",
    "ultima_presenca": 9574536,
    "vai_evadir": "sim"
  },
  // Continuação até 100...
  {
    "nome": "Yasmin Fernandes",
    "idade": 26,
    "contrato_meses": 12,
    "feedback": "não",
    "frequência": 3,
    "genêro": "feminino",
    "id": 151,
    "mes_cancelamento": 5,
    "mes_entrada": 2,
    "status": "cancelado",
    "ultima_presenca": 9374537,
    "vai_evadir": "sim"
  }
];

export default alunas;